#
# Copyright 2014 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


$(call inherit-product-if-exists,$(LOCAL_PATH)/device-vendor.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/languages_full.mk)

DEVICE_PACKAGE_OVERLAYS += device/samsung/j1xlteatt/overlay

LOCAL_PATH := device/samsung/j1xlteatt
ifeq ($(TARGET_PREBUILT_KERNEL),)
	LOCAL_KERNEL := $(LOCAL_PATH)/zImage
else
	LOCAL_KERNEL := $(TARGET_PREBUILT_KERNEL)
endif

$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base.mk)
$(call inherit-product, device/samsung/j1xlteatt/device.mk)

PRODUCT_NAME := full_j1xlteatt
PRODUCT_DEVICE := j1xlteatt
PRODUCT_BRAND := Samsung
PRODUCT_MODEL := j1xlteatt
PRODUCT_MANUFACTURER := samsung
PRODUCT_COPY_FILES += \
$(LOCAL_PATH)/proprietary/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
$(LOCAL_PATH)/proprietary/audio.playback_record.default.so:system/lib/hw/audio.playback_reord.default.so \
$(LOCAL_PATH)/proprietary/audio.primary.goldfish.so:system/lib/hw/audio.primary.goldfish.so \
$(LOCAL_PATH)/proprietary/audio.primary.universal3475.so:system/lib/hw/audio.primary.universl3475.so \
$(LOCAL_PATH)/proprietary/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
$(LOCAL_PATH)/proprietary/audio.tms.default.so:system/lib/hw/audio.tms.default.so \
$(LOCAL_PATH)/proprietary/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
$(LOCAL_PATH)/proprietary/camera.exynos3.so:system/lib/hw/camera.exynos3.so \
$(LOCAL_PATH)/proprietary/camera.goldfish.jpeg.so:system/lib/hw/camera.goldfish.jpeg.so \
$(LOCAL_PATH)/proprietary/camera.goldfish.so:system/lib/hw/camera.goldfish.so \
$(LOCAL_PATH)/proprietary/gatekeeper.exynos3475.so:system/lib/hw/gatekeeper.exynos3475.so \
$(LOCAL_PATH)/proprietary/gps.default.so:system/lib/hw/gps.default.so \
$(LOCAL_PATH)/proprietary/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
$(LOCAL_PATH)/proprietary/gralloc.exynos3.so:system/lib/hw/gralloc.exynos3.so \
$(LOCAL_PATH)/proprietary/hwcomposer.exynos3.so:system/lib/hw/hwcomposer.exynos3.so \
$(LOCAL_PATH)/proprietary/keystore.exynos3475.so:system/lib/hw/keystore.exynos3475.so \
$(LOCAL_PATH)/proprietary/lights.goldfish.so:system/lib/hw/lights.goldfish.so \
$(LOCAL_PATH)/proprietary/memtrack.exynos3.so:system/lib/hw/memtrack.exynos3.so \
$(LOCAL_PATH)/proprietary/power.exynos3.so:system/lib/hw/power.exynos3.so \
$(LOCAL_PATH)/proprietary/power.goldfish.so:system/lib/hw/power.goldfish.so \
$(LOCAL_PATH)/proprietary/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \
$(LOCAL_PATH)/proprietary/sensors.ranchu.so:system/lib/hw/sensors.ranchu.so \
$(LOCAL_PATH)/proprietary/sensors.universal3475.so:system/lib/hw/sensors.universal3475.so \
$(LOCAL_PATH)/proprietary/vibrator.goldfish.so:system/lib/hw/vibrator.goldfish.so \
$(LOCAL_PATH)/proprietary/egl.cfg:system/lib/egl/egl.cfg \
$(LOCAL_PATH)/proprietary/libGLES_android.so:system/lib/egl/libGLES_android.so \
$(LOCAL_PATH)/proprietary/libsgeo.so:system/lib/slocation/libsgeo.so \
$(LOCAL_PATH)/proprietary/libaudiosa_sec.so:system/lib/soundfx/libaudiosa_sec.so \
$(LOCAL_PATH)/proprietary/libmyspace.so:system/lib/soundfx/libmyspace.so \
$(LOCAL_PATH)/proprietary/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
$(LOCAL_PATH)/proprietary/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
$(LOCAL_PATH)/proprietary/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
$(LOCAL_PATH)/proprietary/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
$(LOCAL_PATH)/proprietary/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
$(LOCAL_PATH)/proprietary/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
$(LOCAL_PATH)/proprietary/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
$(LOCAL_PATH)/proprietary/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
$(LOCAL_PATH)/proprietary/libomaplugin.so:system/lib/drm/libomaplugin.so \
$(LOCAL_PATH)/proprietary/lib_DNSe_EP_ver216c.so:system/lib/lib_DNSe_EP_ver216c.so \
$(LOCAL_PATH)/proprietary/lib_DNSe_NRSS_ver226.so:system/lib/lib_DNSe_NRSS_ver226.so \
$(LOCAL_PATH)/proprietary/lib_PreGainBooster_ver105.so:system/lib/lib_PreGainBooster_ver105.so \
$(LOCAL_PATH)/proprietary/lib_SA_GoogleFX_ver119k.so:system/lib/lib_SA_GoogleFX_ver119k.so \
$(LOCAL_PATH)/proprietary/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
$(LOCAL_PATH)/proprietary/lib_SamsungRec_V04013.so:system/lib/lib_SamsungRec_V04013.so \
$(LOCAL_PATH)/proprietary/lib_SamsungVAD_v01009.so:system/lib/lib_SamsungVAD_v01009.so \
$(LOCAL_PATH)/proprietary/lib_SoundAlive_3DPosition_ver107.so:system/lib/lib_SoundAlive_3DPosition_ver107.so \
$(LOCAL_PATH)/proprietary/lib_SoundAlive_3DRendering_ver102.so:system/lib/lib_SoundAlive_3DRendering_ver102.so \
$(LOCAL_PATH)/proprietary/lib_SoundAlive_play_plus_ver126a.so:system/lib/lib_SoundAlive_play_plus_ver126a.so \
$(LOCAL_PATH)/proprietary/lib_SoundAlive_SRC192_ver205.so:system/lib/lib_SoundAlive_SRC192_ver205.so \
$(LOCAL_PATH)/proprietary/lib_SoundAlive_ver118t.so:system/lib/lib_SoundAlive_ver118t.so \
$(LOCAL_PATH)/proprietary/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
$(LOCAL_PATH)/proprietary/lib_SoundBooster_ver610.so:system/lib/lib_SoundBooster_ver610.so \
$(LOCAL_PATH)/proprietary/libabcfingr.so:system/lib/libabcfingr.so \
$(LOCAL_PATH)/proprietary/libaccauthentication_jni.so:system/lib/libaccauthentication_jni.so \
$(LOCAL_PATH)/proprietary/libanalytics.so:system/lib/libanalytics.so \
$(LOCAL_PATH)/proprietary/libandroid_ssrm.so:system/lib/libandroid_ssrm.so \
$(LOCAL_PATH)/proprietary/libAndroidExport_p.so:system/lib/libAndroidExport_p.so \
$(LOCAL_PATH)/proprietary/libarac.so:system/lib/libarac.so \
$(LOCAL_PATH)/proprietary/libarccamera.so:system/lib/libarccamera.so \
$(LOCAL_PATH)/proprietary/libarcsoft_panorama_burstcapture.so:system/lib/libarcsoft_panorama_burstcapture.so \
$(LOCAL_PATH)/proprietary/libarcsoft_selfie_camera_lite.so:system/lib/libarcsoft_selfie_camera_lite.so \
$(LOCAL_PATH)/proprietary/libaresdns.so:system/lib/libaresdns.so \
$(LOCAL_PATH)/proprietary/libasf_fileshare.so:system/lib/libasf_fileshare.so \
$(LOCAL_PATH)/proprietary/libasf_fileshareserver.so:system/lib/libasf_fileshareserver.so \
$(LOCAL_PATH)/proprietary/libAstcEnc.so:system/lib/libAstcEnc.so \
$(LOCAL_PATH)/proprietary/libatomcore.so:system/lib/libatomcore.so \
$(LOCAL_PATH)/proprietary/libatomjpeg.so:system/lib/libatomjpeg.so \
$(LOCAL_PATH)/proprietary/libatparser.so:system/lib/libatparser.so \
$(LOCAL_PATH)/proprietary/libaudio-ril.so:system/lib/libaudio-ril.so \
$(LOCAL_PATH)/proprietary/libaudioroute.so:system/lib/libaudioroute.so \
$(LOCAL_PATH)/proprietary/libaudiosa.so:system/lib/libaudiosa.so \
$(LOCAL_PATH)/proprietary/libAutoEnhance.so:system/lib/libAutoEnhance.so \
$(LOCAL_PATH)/proprietary/libbrnn.so:system/lib/libbrnn.so \
$(LOCAL_PATH)/proprietary/libbrnne_jni.so:system/lib/libbrnne_jni.so \
$(LOCAL_PATH)/proprietary/libbt-aptX-ARM-4.2.2.so:system/lib/libbt-aptX-ARM-4.2.2.so \
$(LOCAL_PATH)/proprietary/libbt-codec_aptx.so:system/lib/libbt-codec_aptx.so \
$(LOCAL_PATH)/proprietary/libbt-codec_sshd.so:system/lib/libbt-codec_sshd.so \
$(LOCAL_PATH)/proprietary/libbt-iopdb.so:system/lib/libbt-iopdb.so \
$(LOCAL_PATH)/proprietary/libbt-iopdb_mod.so:system/lib/libbt-iopdb_mod.so \
$(LOCAL_PATH)/proprietary/libbt-vendor.so:system/lib/libbt-vendor.so \
$(LOCAL_PATH)/proprietary/libcameraservice_cameramodule.so:system/lib/libcameraservice_cameramodule.so \
$(LOCAL_PATH)/proprietary/libcc_manager.so:system/lib/libcc_manager.so \
$(LOCAL_PATH)/proprietary/libcharon.so:system/lib/libcharon.so \
$(LOCAL_PATH)/proprietary/libcodecdump.so:system/lib/libcodecdump.so \
$(LOCAL_PATH)/proprietary/libcommonpawrapper.so:system/lib/libcommonpawrapper.so \
$(LOCAL_PATH)/proprietary/libcontrolcsc.so:system/lib/libcontrolcsc.so \
$(LOCAL_PATH)/proprietary/libcordon.so:system/lib/libcordon.so \
$(LOCAL_PATH)/proprietary/libcpve-client.so:system/lib/libcpve-client.so \
$(LOCAL_PATH)/proprietary/libCreateSceneMap.so:system/lib/libCreateSceneMap.so \
$(LOCAL_PATH)/proprietary/libCryptionkey.so:system/lib/libCryptionkey.so \
$(LOCAL_PATH)/proprietary/libcrypto-rename.so:system/lib/libcrypto-rename.so \
$(LOCAL_PATH)/proprietary/libcsc.so:system/lib/libcsc.so \
$(LOCAL_PATH)/proprietary/libcurl.so:system/lib/libcurl.so \
$(LOCAL_PATH)/proprietary/libcurl2.so:system/lib/libcurl2.so \
$(LOCAL_PATH)/proprietary/libdiagmonagent.so:system/lib/libdiagmonagent.so \
$(LOCAL_PATH)/proprietary/libdirencryption.so:system/lib/libdirencryption.so \
$(LOCAL_PATH)/proprietary/libdisplay.so:system/lib/libdisplay.so \
$(LOCAL_PATH)/proprietary/libdk_native.so:system/lib/libdk_native.so \
$(LOCAL_PATH)/proprietary/libdk_native_client.so:system/lib/libdk_native_client.so \
$(LOCAL_PATH)/proprietary/libdlp_sdk.so:system/lib/libdlp_sdk.so \
$(LOCAL_PATH)/proprietary/libdmcDLFR.so:system/lib/libdmcDLFR.so \
$(LOCAL_PATH)/proprietary/libdmcFaceEngine.so:system/lib/libdmcFaceEngine.so \
$(LOCAL_PATH)/proprietary/libdmcfcEngine.so:system/lib/libdmcfcEngine.so \
$(LOCAL_PATH)/proprietary/libDMCImageMatting.so:system/lib/libDMCImageMatting.so \
$(LOCAL_PATH)/proprietary/libdmcLMDEngine.so:system/lib/libdmcLMDEngine.so \
$(LOCAL_PATH)/proprietary/libdmcMVFD.so:system/lib/libdmcMVFD.so \
$(LOCAL_PATH)/proprietary/libdprwa.so:system/lib/libdprwa.so \
$(LOCAL_PATH)/proprietary/libdrawglfunction.so:system/lib/libdrawglfunction.so \
$(LOCAL_PATH)/proprietary/libDualShotMattingCoreLIB.so:system/lib/libDualShotMattingCoreLIB.so \
$(LOCAL_PATH)/proprietary/libedmnativehelper.so:system/lib/libedmnativehelper.so \
$(LOCAL_PATH)/proprietary/libedmnativehelperservice.so:system/lib/libedmnativehelperservice.so \
$(LOCAL_PATH)/proprietary/libeffectpolicy.so:system/lib/libeffectpolicy.so \
$(LOCAL_PATH)/proprietary/libengmode.so:system/lib/libengmode.so \
$(LOCAL_PATH)/proprietary/libepm.so:system/lib/libepm.so \
$(LOCAL_PATH)/proprietary/libexfat_utils.so:system/lib/libexfat_utils.so \
$(LOCAL_PATH)/proprietary/libexynoscameraexternal.so:system/lib/libexynoscameraexternal.so \
$(LOCAL_PATH)/proprietary/libexynosgscaler.so:system/lib/libexynosgscaler.so \
$(LOCAL_PATH)/proprietary/libExynosHWCService.so:system/lib/libExynosHWCService.so \
$(LOCAL_PATH)/proprietary/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
$(LOCAL_PATH)/proprietary/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
$(LOCAL_PATH)/proprietary/libexynosscaler.so:system/lib/libexynosscaler.so \
$(LOCAL_PATH)/proprietary/libexynosutils.so:system/lib/libexynosutils.so \
$(LOCAL_PATH)/proprietary/libexynosv4l2.so:system/lib/libexynosv4l2.so \
$(LOCAL_PATH)/proprietary/libfactoryutil.so:system/lib/libfactoryutil.so \
$(LOCAL_PATH)/proprietary/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
$(LOCAL_PATH)/proprietary/libgdmcprov.so:system/lib/libgdmcprov.so \
$(LOCAL_PATH)/proprietary/libgen_def_cert.so:system/lib/libgen_def_cert.so \
$(LOCAL_PATH)/proprietary/libhancomgraphics-tf_p.so:system/lib/libhancomgraphics-tf_p.so \
$(LOCAL_PATH)/proprietary/libhancomofficeengine_p.so:system/lib/libhancomofficeengine_p.so \
$(LOCAL_PATH)/proprietary/libhdcp2.so:system/lib/libhdcp2.so \
$(LOCAL_PATH)/proprietary/libhdmi.so:system/lib/libhdmi.so \
$(LOCAL_PATH)/proprietary/libhncimageEffects_p.so:system/lib/libhncimageEffects_p.so \
$(LOCAL_PATH)/proprietary/libhwcutils.so:system/lib/libhwcutils.so \
$(LOCAL_PATH)/proprietary/libhwjpeg.so:system/lib/libhwjpeg.so \
$(LOCAL_PATH)/proprietary/libhydra.so:system/lib/libhydra.so \
$(LOCAL_PATH)/proprietary/libInteractivePanoramaUtil.so:system/lib/libInteractivePanoramaUtil.so \
$(LOCAL_PATH)/proprietary/libion.so:system/lib/libion.so \
$(LOCAL_PATH)/proprietary/libion_exynos.so:system/lib/libion_exynos.so \
$(LOCAL_PATH)/proprietary/libjni_ipsecservice.so:system/lib/libjni_ipsecservice.so \
$(LOCAL_PATH)/proprietary/libkerberos.so:system/lib/libkerberos.so \
$(LOCAL_PATH)/proprietary/libknox_encryption.so:system/lib/libknox_encryption.so \
$(LOCAL_PATH)/proprietary/libknox_km.so:system/lib/libknox_km.so \
$(LOCAL_PATH)/proprietary/libknox_legacy_ode_km.so:system/lib/libknox_legacy_ode_km.so \
$(LOCAL_PATH)/proprietary/libknox_migration.so:system/lib/libknox_migration.so \
$(LOCAL_PATH)/proprietary/libknoxvpnfdsender.so:system/lib/libknoxvpnfdsender.so \
$(LOCAL_PATH)/proprietary/libmaet.so:system/lib/libmaet.so \
$(LOCAL_PATH)/proprietary/libMcClient.so:system/lib/libMcClient.so \
$(LOCAL_PATH)/proprietary/libMcRegistry.so:system/lib/libMcRegistry.so \
$(LOCAL_PATH)/proprietary/libmctraster.so:system/lib/libmctraster.so \
$(LOCAL_PATH)/proprietary/libMLDAP.so:system/lib/libMLDAP.so \
$(LOCAL_PATH)/proprietary/libMMCodec.so:system/lib/libMMCodec.so \
$(LOCAL_PATH)/proprietary/libMP4Converter.so:system/lib/libMP4Converter.so \
$(LOCAL_PATH)/proprietary/libmpp.so:system/lib/libmpp.so \
$(LOCAL_PATH)/proprietary/libmtp_samsung.so:system/lib/libmtp_samsung.so \
$(LOCAL_PATH)/proprietary/libmtp_samsung_jni.so:system/lib/libmtp_samsung_jni.so \
$(LOCAL_PATH)/proprietary/libmysound.so:system/lib/libmysound.so \
$(LOCAL_PATH)/proprietary/libnativemr.so:system/lib/libnativemr.so \
$(LOCAL_PATH)/proprietary/libnvaccessor_fb.so:system/lib/libnvaccessor_fb.so \
$(LOCAL_PATH)/proprietary/libomacp.so:system/lib/libomacp.so \
$(LOCAL_PATH)/proprietary/libomafldrm.so:system/lib/libomafldrm.so \
$(LOCAL_PATH)/proprietary/libomission_avoidance.so:system/lib/libomission_avoidance.so \
$(LOCAL_PATH)/proprietary/libOpenCv.so:system/lib/libOpenCv.so \
$(LOCAL_PATH)/proprietary/libpadm.so:system/lib/libpadm.so \
$(LOCAL_PATH)/proprietary/libpalmMobileDetectorFull.so:system/lib/libpalmMobileDetectorFull.so \
$(LOCAL_PATH)/proprietary/libpersona.so:system/lib/libpersona.so \
$(LOCAL_PATH)/proprietary/libphotoeditorEngine.so:system/lib/libphotoeditorEngine.so \
$(LOCAL_PATH)/proprietary/libpreprocessing_nxp.so:system/lib/libpreprocessing_nxp.so \
$(LOCAL_PATH)/proprietary/libprintspooler_jni6.so:system/lib/libprintspooler_jni6.so \
$(LOCAL_PATH)/proprietary/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
$(LOCAL_PATH)/proprietary/libQjpeg.so:system/lib/libQjpeg.so \
$(LOCAL_PATH)/proprietary/libqjpeg_secvision.so:system/lib/libqjpeg_secvision.so \
$(LOCAL_PATH)/proprietary/libQmageDecoder.so:system/lib/libQmageDecoder.so \
$(LOCAL_PATH)/proprietary/libquramagifencoder_L.so:system/lib/libquramagifencoder_L.so \
$(LOCAL_PATH)/proprietary/libquramimagecodec.so:system/lib/libquramimagecodec.so \
$(LOCAL_PATH)/proprietary/libquramresize.so:system/lib/libquramresize.so \
$(LOCAL_PATH)/proprietary/libremotedesktop_client.so:system/lib/libremotedesktop_client.so \
$(LOCAL_PATH)/proprietary/libremotedesktopservice.so:system/lib/libremotedesktopservice.so \
$(LOCAL_PATH)/proprietary/librtmpstack.so:system/lib/librtmpstack.so \
$(LOCAL_PATH)/proprietary/libsafezone-sw-fips-1.1.so:system/lib/libsafezone-sw-fips-1.1.so \
$(LOCAL_PATH)/proprietary/libsaiv.so:system/lib/libsaiv.so \
$(LOCAL_PATH)/proprietary/libsaiv_codec.so:system/lib/libsaiv_codec.so \
$(LOCAL_PATH)/proprietary/libsaiv_face_api.so:system/lib/libsaiv_face_api.so \
$(LOCAL_PATH)/proprietary/libsaiv_face_jni.so:system/lib/libsaiv_face_jni.so \
$(LOCAL_PATH)/proprietary/libsaiv_vision.so:system/lib/libsaiv_vision.so \
$(LOCAL_PATH)/proprietary/libsAMRNB.so:system/lib/libsAMRNB.so \
$(LOCAL_PATH)/proprietary/libsAMRWB.so:system/lib/libsAMRWB.so \
$(LOCAL_PATH)/proprietary/libsamsungDiamondVoiceExt.so:system/lib/libsamsungDiamondVoiceExt.so \
$(LOCAL_PATH)/proprietary/libsamsungearcare.so:system/lib/libsamsungearcare.so \
$(LOCAL_PATH)/proprietary/libsamsungeffect.so:system/lib/libsamsungeffect.so \
$(LOCAL_PATH)/proprietary/libSamsungMusic_v5.so:system/lib/libSamsungMusic_v5.so \
$(LOCAL_PATH)/proprietary/libSamsungPkcs11Wrapper.so:system/lib/libSamsungPkcs11Wrapper.so \
$(LOCAL_PATH)/proprietary/libSamsungPostProcess.so:system/lib/libSamsungPostProcess.so \
$(LOCAL_PATH)/proprietary/libSamsungPostProcessConvertor.so:system/lib/libSamsungPostProcessConvertor.so \
$(LOCAL_PATH)/proprietary/libsamsungpowersound.so:system/lib/libsamsungpowersound.so \
$(LOCAL_PATH)/proprietary/libSamsungPreProcess.so:system/lib/libSamsungPreProcess.so \
$(LOCAL_PATH)/proprietary/libsamsungRecord.so:system/lib/libsamsungRecord.so \
$(LOCAL_PATH)/proprietary/libsamsungRecord_ns.so:system/lib/libsamsungRecord_ns.so \
$(LOCAL_PATH)/proprietary/libsamsungSoundbooster_ext.so:system/lib/libsamsungSoundbooster_ext.so \
$(LOCAL_PATH)/proprietary/libsamsungSoundbooster_pgb.so:system/lib/libsamsungSoundbooster_pgb.so \
$(LOCAL_PATH)/proprietary/libsamsungvad.so:system/lib/libsamsungvad.so \
$(LOCAL_PATH)/proprietary/libsavsac.so:system/lib/libsavsac.so \
$(LOCAL_PATH)/proprietary/libsavscmn.so:system/lib/libsavscmn.so \
$(LOCAL_PATH)/proprietary/libsavsff.so:system/lib/libsavsff.so \
$(LOCAL_PATH)/proprietary/libsavsmeta.so:system/lib/libsavsmeta.so \
$(LOCAL_PATH)/proprietary/libsavsvc.so:system/lib/libsavsvc.so \
$(LOCAL_PATH)/proprietary/libsccore.so:system/lib/libsccore.so \
$(LOCAL_PATH)/proprietary/libsdp_crypto.so:system/lib/libsdp_crypto.so \
$(LOCAL_PATH)/proprietary/libsdp_kekm.so:system/lib/libsdp_kekm.so \
$(LOCAL_PATH)/proprietary/libsdp_sdk.so:system/lib/libsdp_sdk.so \
$(LOCAL_PATH)/proprietary/libseams_binder.so:system/lib/libseams_binder.so \
$(LOCAL_PATH)/proprietary/libsec_devenc.so:system/lib/libsec_devenc.so \
$(LOCAL_PATH)/proprietary/libsec_ecryptfs.so:system/lib/libsec_ecryptfs.so \
$(LOCAL_PATH)/proprietary/libsec_km.so:system/lib/libsec_km.so \
$(LOCAL_PATH)/proprietary/libsec_ode_keymanager.so:system/lib/libsec_ode_keymanager.so \
$(LOCAL_PATH)/proprietary/libsec_ode_migration.so:system/lib/libsec_ode_migration.so \
$(LOCAL_PATH)/proprietary/libseccamera_jni.so:system/lib/libseccamera_jni.so \
$(LOCAL_PATH)/proprietary/libseccameracore.so:system/lib/libseccameracore.so \
$(LOCAL_PATH)/proprietary/libsecface.so:system/lib/libsecface.so \
$(LOCAL_PATH)/proprietary/libsecfips.so:system/lib/libsecfips.so \
$(LOCAL_PATH)/proprietary/libsechelper_engine.so:system/lib/libsechelper_engine.so \
$(LOCAL_PATH)/proprietary/libsecimaging.so:system/lib/libsecimaging.so \
$(LOCAL_PATH)/proprietary/libsec-ims.so:system/lib/libsec-ims.so \
$(LOCAL_PATH)/proprietary/libsecjpeginterface.so:system/lib/libsecjpeginterface.so \
$(LOCAL_PATH)/proprietary/libsecjpegquram.so:system/lib/libsecjpegquram.so \
$(LOCAL_PATH)/proprietary/libseckeyprov.so:system/lib/libseckeyprov.so \
$(LOCAL_PATH)/proprietary/libsecmediarecorder_jni.so:system/lib/libsecmediarecorder_jni.so \
$(LOCAL_PATH)/proprietary/libSecMMCodec.so:system/lib/libSecMMCodec.so \
$(LOCAL_PATH)/proprietary/libsecnativefeature.so:system/lib/libsecnativefeature.so \
$(LOCAL_PATH)/proprietary/libsecopenssl_engine.so:system/lib/libsecopenssl_engine.so \
$(LOCAL_PATH)/proprietary/libsecpkcs11_engine.so:system/lib/libsecpkcs11_engine.so \
$(LOCAL_PATH)/proprietary/libsec-ril.so:system/lib/libsec-ril.so \
$(LOCAL_PATH)/proprietary/libsecril-client.so:system/lib/libsecril-client.so \
$(LOCAL_PATH)/proprietary/libsecuibc.so:system/lib/libsecuibc.so \
$(LOCAL_PATH)/proprietary/libsecure_storage.so:system/lib/libsecure_storage.so \
$(LOCAL_PATH)/proprietary/libsecure_storage_jni.so:system/lib/libsecure_storage_jni.so \
$(LOCAL_PATH)/proprietary/libSecurityManagerNative.so:system/lib/libSecurityManagerNative.so \
$(LOCAL_PATH)/proprietary/libSEF.so:system/lib/libSEF.so \
$(LOCAL_PATH)/proprietary/libSEF4MP4.so:system/lib/libSEF4MP4.so \
$(LOCAL_PATH)/proprietary/libsetproperty.so:system/lib/libsetproperty.so \
$(LOCAL_PATH)/proprietary/libsfextaac.so:system/lib/libsfextaac.so \
$(LOCAL_PATH)/proprietary/libsfextavi.so:system/lib/libsfextavi.so \
$(LOCAL_PATH)/proprietary/libsfextcmn.so:system/lib/libsfextcmn.so \
$(LOCAL_PATH)/proprietary/libsfextcp.so:system/lib/libsfextcp.so \
$(LOCAL_PATH)/proprietary/libsfextflac.so:system/lib/libsfextflac.so \
$(LOCAL_PATH)/proprietary/libsfextflv.so:system/lib/libsfextflv.so \
$(LOCAL_PATH)/proprietary/libsfextmkv.so:system/lib/libsfextmkv.so \
$(LOCAL_PATH)/proprietary/libsfextmp4f.so:system/lib/libsfextmp4f.so \
$(LOCAL_PATH)/proprietary/libsfextrmf.so:system/lib/libsfextrmf.so \
$(LOCAL_PATH)/proprietary/libsfextwmf.so:system/lib/libsfextwmf.so \
$(LOCAL_PATH)/proprietary/libshdace.so:system/lib/libshdace.so \
$(LOCAL_PATH)/proprietary/libsimageis_jni.so:system/lib/libsimageis_jni.so \
$(LOCAL_PATH)/proprietary/libskia_tf_p.so:system/lib/libskia_tf_p.so \
$(LOCAL_PATH)/proprietary/libskmm.so:system/lib/libskmm.so \
$(LOCAL_PATH)/proprietary/libskmm_helper.so:system/lib/libskmm_helper.so \
$(LOCAL_PATH)/proprietary/libSLinkNTSMngr_jni.so:system/lib/libSLinkNTSMngr_jni.so \
$(LOCAL_PATH)/proprietary/libsmart_cropping.so:system/lib/libsmart_cropping.so \
$(LOCAL_PATH)/proprietary/libSmartClipEffect.so:system/lib/libSmartClipEffect.so \
$(LOCAL_PATH)/proprietary/libSmartVolumeLib.so:system/lib/libSmartVolumeLib.so \
$(LOCAL_PATH)/proprietary/libsmejni.so:system/lib/libsmejni.so \
$(LOCAL_PATH)/proprietary/libsnaace.so:system/lib/libsnaace.so \
$(LOCAL_PATH)/proprietary/libsnamrnb.so:system/lib/libsnamrnb.so \
$(LOCAL_PATH)/proprietary/libsnamrwb.so:system/lib/libsnamrwb.so \
$(LOCAL_PATH)/proprietary/libsomp.so:system/lib/libsomp.so \
$(LOCAL_PATH)/proprietary/libsomx263dsw.so:system/lib/libsomx263dsw.so \
$(LOCAL_PATH)/proprietary/libsomx264dsw.so:system/lib/libsomx264dsw.so \
$(LOCAL_PATH)/proprietary/libsomxaacd.so:system/lib/libsomxaacd.so \
$(LOCAL_PATH)/proprietary/libsomxaace.so:system/lib/libsomxaace.so \
$(LOCAL_PATH)/proprietary/libsomxadpcmd.so:system/lib/libsomxadpcmd.so \
$(LOCAL_PATH)/proprietary/libsomxamrd.so:system/lib/libsomxamrd.so \
$(LOCAL_PATH)/proprietary/libsomxcmn.so:system/lib/libsomxcmn.so \
$(LOCAL_PATH)/proprietary/libsomxcore.so:system/lib/libsomxcore.so \
$(LOCAL_PATH)/proprietary/libsomxflacd.so:system/lib/libsomxflacd.so \
$(LOCAL_PATH)/proprietary/libsomxhevcdsw.so:system/lib/libsomxhevcdsw.so \
$(LOCAL_PATH)/proprietary/libsomxmp3d.so:system/lib/libsomxmp3d.so \
$(LOCAL_PATH)/proprietary/libsomxmp43d.so:system/lib/libsomxmp43d.so \
$(LOCAL_PATH)/proprietary/libsomxmp4vdsw.so:system/lib/libsomxmp4vdsw.so \
$(LOCAL_PATH)/proprietary/libsomxnaace.so:system/lib/libsomxnaace.so \
$(LOCAL_PATH)/proprietary/libsomxsr263d.so:system/lib/libsomxsr263d.so \
$(LOCAL_PATH)/proprietary/libsomxvc1dsw.so:system/lib/libsomxvc1dsw.so \
$(LOCAL_PATH)/proprietary/libsomxvencsw.so:system/lib/libsomxvencsw.so \
$(LOCAL_PATH)/proprietary/libsomxvp8d.so:system/lib/libsomxvp8d.so \
$(LOCAL_PATH)/proprietary/libsomxwmad.so:system/lib/libsomxwmad.so \
$(LOCAL_PATH)/proprietary/libsomxwmv7d.so:system/lib/libsomxwmv7d.so \
$(LOCAL_PATH)/proprietary/libsomxwmv8d.so:system/lib/libsomxwmv8d.so \
$(LOCAL_PATH)/proprietary/libsoundalive.so:system/lib/libsoundalive.so \
$(LOCAL_PATH)/proprietary/libSoundAlive_VSP_ver315b_arm.so:system/lib/libSoundAlive_VSP_ver315b_arm.so \
$(LOCAL_PATH)/proprietary/libsoundspeed.so:system/lib/libsoundspeed.so \
$(LOCAL_PATH)/proprietary/libspdkeygen.so:system/lib/libspdkeygen.so \
$(LOCAL_PATH)/proprietary/libSRIBSE_Interface.so:system/lib/libSRIBSE_Interface.so \
$(LOCAL_PATH)/proprietary/libSRIBSE_Lib.so:system/lib/libSRIBSE_Lib.so \
$(LOCAL_PATH)/proprietary/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
$(LOCAL_PATH)/proprietary/libstagefrighthw.so:system/lib/libstagefrighthw.so \
$(LOCAL_PATH)/proprietary/libsthmb.so:system/lib/libsthmb.so \
$(LOCAL_PATH)/proprietary/libstrongswan.so:system/lib/libstrongswan.so \
$(LOCAL_PATH)/proprietary/libsveservice.so:system/lib/libsveservice.so \
$(LOCAL_PATH)/proprietary/libsxqk.so:system/lib/libsxqk.so \
$(LOCAL_PATH)/proprietary/libsxqk_skia.so:system/lib/libsxqk_skia.so \
$(LOCAL_PATH)/proprietary/libterrier.so:system/lib/libterrier.so \
$(LOCAL_PATH)/proprietary/libtfbidi_p.so:system/lib/libtfbidi_p.so \
$(LOCAL_PATH)/proprietary/libTFDrawingSDK_p.so:system/lib/libTFDrawingSDK_p.so \
$(LOCAL_PATH)/proprietary/libtfexternal_p.so:system/lib/libtfexternal_p.so \
$(LOCAL_PATH)/proprietary/libtffont2_p.so:system/lib/libtffont2_p.so \
$(LOCAL_PATH)/proprietary/libtfimage_p.so:system/lib/libtfimage_p.so \
$(LOCAL_PATH)/proprietary/libTfoWrite_p.so:system/lib/libTfoWrite_p.so \
$(LOCAL_PATH)/proprietary/libtinycompress.so:system/lib/libtinycompress.so \
$(LOCAL_PATH)/proprietary/libtlc_comm.so:system/lib/libtlc_comm.so \
$(LOCAL_PATH)/proprietary/libtlc_proxy.so:system/lib/libtlc_proxy.so \
$(LOCAL_PATH)/proprietary/libtlc_proxy_tui.so:system/lib/libtlc_proxy_tui.so \
$(LOCAL_PATH)/proprietary/libtlc_t2_ks_mi.so:system/lib/libtlc_t2_ks_mi.so \
$(LOCAL_PATH)/proprietary/libtlc_tima_atn.so:system/lib/libtlc_tima_atn.so \
$(LOCAL_PATH)/proprietary/libtlc_tima_pkm.so:system/lib/libtlc_tima_pkm.so \
$(LOCAL_PATH)/proprietary/libtlc_tima_tui.so:system/lib/libtlc_tima_tui.so \
$(LOCAL_PATH)/proprietary/libtlc_tz_ccm.so:system/lib/libtlc_tz_ccm.so \
$(LOCAL_PATH)/proprietary/libtlc_tz_iccc.so:system/lib/libtlc_tz_iccc.so \
$(LOCAL_PATH)/proprietary/libtlc_tz_keystore.so:system/lib/libtlc_tz_keystore.so \
$(LOCAL_PATH)/proprietary/libtlcotp.so:system/lib/libtlcotp.so \
$(LOCAL_PATH)/proprietary/libtwomicinterface.so:system/lib/libtwomicinterface.so \
$(LOCAL_PATH)/proprietary/libtzyfingr.so:system/lib/libtzyfingr.so \
$(LOCAL_PATH)/proprietary/libucsengine.so:system/lib/libucsengine.so \
$(LOCAL_PATH)/proprietary/libucsengineode.so:system/lib/libucsengineode.so \
$(LOCAL_PATH)/proprietary/libunshorten.so:system/lib/libunshorten.so \
$(LOCAL_PATH)/proprietary/libVideoEngine.so:system/lib/libVideoEngine.so \
$(LOCAL_PATH)/proprietary/libwpa_client.so:system/lib/libwpa_client.so \
$(LOCAL_PATH)/proprietary/libwrappergps.so:system/lib/libwrappergps.so \
$(LOCAL_PATH)/proprietary/libxml2.so:system/lib/libxml2.so \
$(LOCAL_PATH)/proprietary/audience-es804-fw.bin:system/etc/firmware/audience-es804-fw.bin \
$(LOCAL_PATH)/proprietary/iop_bt.db:system/etc/bluetooth/iop_bt.db \
$(LOCAL_PATH)/proprietary/iop_device_list.conf:system/etc/bluetooth/iop_device_list.conf \
$(LOCAL_PATH)/proprietary/audience-es804-fw.bin:system/etc/firmware/audience-es804-fw.bin \
$(LOCAL_PATH)/proprietary/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
$(LOCAL_PATH)/proprietary/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
$(LOCAL_PATH)/proprietary/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
$(LOCAL_PATH)/proprietary/cred.conf:system/etc/wifi/cred.conf \
$(LOCAL_PATH)/proprietary/default_ap.conf:system/etc/wifi/default_ap.conf \
$(LOCAL_PATH)/proprietary/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
$(LOCAL_PATH)/proprietary/nvram_net.txt:system/etc/wifi/nvram_net.txt \
$(LOCAL_PATH)/proprietary/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
$(LOCAL_PATH)/proprietary/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
$(LOCAL_PATH)/proprietary/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
$(LOCAL_PATH)/proprietary/gps.conf:system/etc/gps.conf \
$(LOCAL_PATH)/proprietary/gps.xml:system/etc/gps.xml \
$(LOCAL_PATH)/proprietary/init.goldfish.sh:system/etc/init.goldfish.sh \
$(LOCAL_PATH)/proprietary/init.sec.boot.sh:system/etc/init.sec.boot.sh \
$(LOCAL_PATH)/michael_mic.ko:root/michael_mic.ko \
$(LOCAL_PATH)/i2c-stub.ko:root/i2c-stub.ko \
$(LOCAL_PATH)/comedi.ko:root/comedi.ko \
$(LOCAL_PATH)/kcomedilib.ko:root/kcomedilib.ko \
$(LOCAL_PATH)/comedi_bond.ko:root/comedi_bond.ko \
$(LOCAL_PATH)/comedi_test.ko:root/comedi_test.ko \
$(LOCAL_PATH)/comedi_parport.ko:root/comedi_parport.ko \
$(LOCAL_PATH)/serial2002.ko:root/serial2002.ko \
$(LOCAL_PATH)/skel.ko:root/skel.ko \
$(LOCAL_PATH)/dt9812.ko:root/dt9812.ko \
$(LOCAL_PATH)/usbdux.ko:root/usbdux.ko \
$(LOCAL_PATH)/usbduxfast.ko:root/usbduxfast.ko \
$(LOCAL_PATH)/usbduxsigma.ko:root/usbduzsigma.ko \
$(LOCAL_PATH)/vmk80xx.ko:root/vmk80xx.ko \
$(LOCAL_PATH)/8255.ko:root/8255.ko \
$(LOCAL_PATH)/comedi_fc.ko:root/comedi_fc.ko \
$(LOCAL_PATH)/vt6656_stage.ko:root/vt6656_stage.ko \
$(LOCAL_PATH)/lib80211.ko:root/lib80211.ko \
$(LOCAL_PATH)/init.recovery.universal3475.rc:root/init.recovery.samsungexynos3475.rc \
$(LOCAL_PATH)/recovery.fstab:recovery/root/etc/recovery.fstab \
$(LOCAL_KERNEL):kernel \


